# -*- coding: utf-8 -*-
"""Evidencia 2. Proyecto de Ciencia de Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jp_VVzf8DF-iwZjU_LFtaFlGd13JCuTE

"""**Se importa librería pandas y se lee el archivo**
"""

import pandas as pd

#Se asignan los datos del excel a la variable datos_consumo
datos_consumo = pd.read_excel('datos.xlsx') 

#Se comprueba que se hayan cargado correctamente
datos_consumo.head()

"""**Limpieza de datos**"""

#Se asigna a datos solamente los datos que vamos a necesitar
datos = datos_consumo[["Fecha (dd/mm/aa)","Calorías (kcal)"]]

#Se comprueba que se hayan cargado correctamente
datos.head()

"""**Promedio**"""

#Se suman total de calorías consumidas
suma_calorias = datos["Calorías (kcal)"].sum()
suma_calorias

#Total de días de diferentes consumo
dias = datos["Fecha (dd/mm/aa)"].nunique()
dias

#Se calcula el promedio de calorías
calorias_promedio = suma_calorias/dias
print("Se consumió un total de",suma_calorias,"calorías en ese periodo.","\n"+"El promedio de calorías consumidas en", dias, "días es", calorias_promedio, "al día." )

"""**Cálculo de la ecuación**"""

#Input de la información del usuario
peso = int(input("Ingresa tu peso en kilogramos: "))
altura = int(input("Ingresa tu altura en centimetros: "))
edad = int(input("Ingresa tu edad en años: "))
sexo = input("Ingresa el sexo biologico al que más te acerques (Femenino, Masculino): ")

#Estimación con la ecuación de Harris-Benedict
if(sexo == "Femenino"):
  calorias_requeridas = 655+(9.56*peso)+(1.85*altura)-(4.68*edad)
  print("Con base en tus datos, tu consumo de calorías al día debe ser de:", calorias_requeridas)
elif(sexo == "Masculino"):
  calorias_requeridas = 66.5+(13.75*peso)+(5*altura)-(6.8*edad)
  print("Con base en tus datos, tu consumo de calorías al día debe ser de:", calorias_requeridas)
else:
  print("Por favor ingresa 'Femenino' o 'Masculino'.")

"""**Cálculo de diferencia**"""

diferencia = calorias_promedio - calorias_requeridas

if(diferencia<0):
  print("Has consumido",(diferencia*-1),"menos de las que requieres en promedio.")
elif(diferencia>=0):
  print("Has consumido",(diferencia*1),"más de las que requieres en promedio.")
else:
  print("Error")

"""**Aproximación de su efecto en un año**"""

efecto_anual = diferencia * 450/3500 * 365 /1000

print("Si continuas con el consumo calórico actual, en un año tu cambio de masa corporal sería aproximadamente de:",efecto_anual,"kg")
print("\n\n(Este resultado no toma en cuenta otros factores importantes como sueño, genética, etc. \nConsulta a tu doctorx antes de tomar decisiones sobre tu salud.)")