# -*- coding: utf-8 -*-
"""fase4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQbvii4WLIjvi83z6DLop9zH27Ir6PFm

**Cargando datos**
"""

import pandas as pd

datos_consumo = pd.read_excel('datos.xlsx')

datos_consumo.head()

datos_consumo.groupby("Momento").count()

datos_consumo.describe()

"""**Seleccionando los datos**"""

datos_seleccionados = datos_consumo.iloc[:,3:8]

datos_seleccionados

"""**Limpiando los datos**"""

datos_seleccionados.isnull().values.any()

dataset = datos_seleccionados.dropna()

dataset.isnull().sum()

"""**Preparando los datos**"""

dataset.columns

X = dataset[['Carbohidratos (g)', 'Lípidos/grasas (g)', 'Proteína (g)', 'Sodio (mg)']].values

y = dataset['Calorías (kcal)'].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

"""**Modelación de los datos**"""

from sklearn.linear_model import LinearRegression

modelo_regresion = LinearRegression()

modelo_regresion.fit(X_train, y_train)

x_columns = ['Carbohidratos (g)', 'Lípidos/grasas (g)', 'Proteína (g)', 'Sodio (mg)']
coeff_df = pd.DataFrame(modelo_regresion.coef_, x_columns, columns=['Coeficientes'])
coeff_df

y_pred = modelo_regresion.predict(X_test)

validacion = pd.DataFrame({'Actual': y_test, 'Predicción': y_pred, 'Diferencia': y_test-y_pred})

muestra_validacion = validacion.head(25)

muestra_validacion

validacion["Diferencia"].describe()

from sklearn import metrics

import numpy as np

print("Raíz de la desviación media al cuadrado:", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

"""**Visualización de los datos**"""

import matplotlib.pyplot as plt

muestra_validacion.plot.bar(rot=0) 

plt.title("Comparación de calorías actuales y de predicción") 

plt.xlabel("Muestra de alimentos")

plt.ylabel("Cantidad de calorías") 

plt.show()