# -*- coding: utf-8 -*-
"""Fase 3: Preparación de los datos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pu1gFZhf8E0ZfB8Fx8Ne81MZLsYBO3vK
"""

#Fase 3: Preparación de los datos 

import pandas as pd

datos_consumo = pd.read_excel("datos.xlsx")

datos_consumo.head()

datos_consumo.groupby("Momento").count()

datos_consumo.describe()

datos_seleccionados = datos_consumo.iloc[:,3:8]

datos_seleccionados

datos_seleccionados.info()

datos_seleccionados.isnull().values.any() 
dataset = datos_seleccionados.dropna() 
dataset.isnull().sum()

dataset.columns

X = dataset[["Carbohidratos (g)","Lípidos/grasas (g)","Proteína (g)","Sodio (mg)"]].values

y = dataset["Calorías (kcal)"].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)